/* 5.- Mostrar el nombre del conductor, el celular y el vehículo que conduce, el conductor que más viajes ha realizado */

SELECT
    C.NOMBRE_CONDUCTOR || ' ' || C.APELLIDO_CONDUCTOR AS NOMBRE_CONDUCTOR,
    V.PLACA_VEHICULO || ' (' || V.MARCA_VEHICULO || ' ' || V.MODELO_VEHICULO || ')' AS VEHICULO,
    COUNT(P.ID_PEDIDO) AS NUMERO_PEDIDOS_REALIZADOS
FROM
    CONDUCTOR C
INNER JOIN
    VEHICULO V ON C.ID_CONDUCTOR = V.ID_CONDUCTOR
LEFT JOIN
    PEDIDO P ON C.ID_CONDUCTOR = P.ID_CONDUCTOR
GROUP BY
    C.ID_CONDUCTOR, NOMBRE_CONDUCTOR, APELLIDO_CONDUCTOR, V.PLACA_VEHICULO, V.MARCA_VEHICULO, V.MODELO_VEHICULO
ORDER BY
    NUMERO_PEDIDOS_REALIZADOS DESC;
